add_newline = true

[git_branch]
symbol = " "

[cmd_duration]
format = '\[[⏱ $duration ]($style)\]'

[conda]
symbol = " "
format = '\[[$symbol$environment]($style)\]'

[python]
symbol = " "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[aws]
disabled = true
